language: generic
install:
  # install pre-compiled flutter
  - FLUTTER_CHANNEL=stable
  - FLUTTER_VERSION=1.0.0-${FLUTTER_CHANNEL}
  - |
    sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null
    wget --quiet --output-document=flutter.tar.xz https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/linux/flutter_linux_v${FLUTTER_VERSION}.tar.xz
    tar xf flutter.tar.xz > /dev/null
    rm flutter.tar.xz
    export PATH="$PATH":"$HOME/.pub-cache/bin"
    export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor -v

  # install sauce labs runner
  - SAUCE_RUNNER_VERSION=0.0.17
  - SAUCE_RUNNER=sauce-runner-virtual-$SAUCE_RUNNER_VERSION-linux
  - |
    wget --quiet https://saucelabs.com/downloads/$SAUCE_RUNNER.zip
    unzip -qq $SAUCE_RUNNER.zip > /dev/null
    rm $SAUCE_RUNNER.zip
    export PATH="$PATH":"$PWD/$SAUCE_RUNNER/bin"

before_script:
  # setup android/local.properties
  - export FLUTTER_ROOT=$PWD/flutter
  - flutter packages get
  - dart tool/setup_local_properties.dart
  # build apks required by espresso
  - |
    cd android
    ./gradlew assembleAndroidTest assembleDebug

script:
  # run espresso in sauce labs
  - sauce-runner-virtual -u $SAUCE_USER -f espresso -a build/app/outputs/apk/debug/app-debug.apk -t build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk -d 'deviceName=Google Pixel GoogleAPI Emulator,platformVersion=7.0'